Use translated scope in Archive because we should
I came across this because I get an exception "ActionView::Template::Error: undefined method `html_safe' for nil:NilClass"
which is caused by `truncate(...)` returning nil on line https://github.com/refinery/refinerycms-news/blob/master/app/helpers/refinery/news/items_helper.rb#L24

Easily reproducable by having 2 locales and create a news item in one language but not the 2nd, then switching to the 2nd locale to view the Archive page, it would crash because it loads some news items with 'item.body == nil' (causing `truncate(item.body)` to be nil).

There are validations for News::Item so we just need to make sure to load only valid records